
name: Ambiente Desenvolvimento

on: 
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
      name: Compilação
      runs-on: ubuntu-latest
    
      steps:
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Configurar o JDK 11
            uses: actions/setup-java@v3
            with: 
              java-version: '11'
              distribution: 'temurin'
              cache: maven
          - name: Compilação
            run: mvn -B compile --file pom.xml

  code-quality:
        name: Análise SonarCloud
        needs: build
        runs-on: ubuntu-latest
        
        steps:
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Adiciona permissão para maven
            run: chmod +x mvnw
          - name: Análise do SonarCloud
            run: ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lab-devops-project -Dsonar.host.url=https://sonarcloud.io/
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              
  tests:
      name: Testes Automatizados
      needs: code-quality
      runs-on: ubuntu-latest

      steps:
        - name: Git checkout
          uses: actions/checkout@v3
        - name: Configurar o JDK 11
          uses: actions/setup-java@v3
          with: 
            java-version: '11'
            distribution: 'temurin'
            cache: maven
        - name: Testes Unitários
          run: mvn -B test --file pom.xml
          
  
  push-image:
      name: Enviar imagem para o Heroku
      needs: tests
      runs-on: ubuntu-latest
      
      steps:
       - name: Prepara ambiente Docker
         uses: docker/setup-buildx-action@v2
         with:
           install: true
       - name: Login no Heroku
         uses: docker/login-action@v2
         with:
           registry: registry.heroku.com
           username: ${{ secrets.HEROKU_EMAIL }}
           password: ${{ secrets.HEROKU_API_KEY }}
       - name: Criação e envio da imagem
         uses: docker/build-push-action@v3
         with:
           push: true
           tags: registry.heroku.com/hands-on-devops-crescer/web:latest

   
