
name: Ambiente Desenvolvimento

on: 
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build:
      name: Compilação
      runs-on: ubuntu-latest
    
      steps:
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Configurar o JDK 11
            uses: actions/setup-java@v3
            with: 
              java-version: '11'
              distribution: 'temurin'
              cache: maven
          - name: Compilação
            run: mvn -B compile --file pom.xml

  code-quality:
        name: Análise SonarCloud
        needs: build
        runs-on: ubuntu-latest
        
        steps:
          - name: Git checkout
            uses: actions/checkout@v3
          - name: Adiciona permissão para maven
            run: chmod +x mvnw
          - name: Análise do SonarCloud
            run: ./mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lab-devops-project
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

