name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  SayHello:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkou@v3
      
      - name: Say it
        run: echo Hello, World!
